### PR TITLE
Maximizing the desktop application window upon opening

### PR DESCRIPTION
**Pull request by quintushr**
Maximizing the desktop application window upon opening

### CODE REVIEW

**Comment by quintushr** [comment]
Hi @perry-mitchell , do you think that maximizing the window or not upon launch should be in the settings, or should it be the default setting ?

**Comment by perry-mitchell** [comment]
Hi @quintushr - thanks for the PR. This should definitely be behind a setting and _not_ be the default.

**Comment by quintushr** [comment]
I saved the maximize state of the window, whether it was maximized or not, and upon launch, it is initialized with the parameter.

Is it better like this ?

**Comment by perry-mitchell** [comment]
Yep, this is great! Thanks.

**Review by perry-mitchell — APPROVED** [review]

**Pull request merged**
