### PR TITLE
feat: check master password strength when creating a new archive.

### PR DESCRIPTION
**Pull request by antoine-amara**
to be more secure, check the master password strength when creating an archive
and return an error if the password doesn't follow the security
recommendations.

for that, follow the main recommendations from the OWASP association.
the master password should now contain:
  - one uppercase letter.
  - one lowercase letter.
  - one number.
  - one special character.

Fixes: https://github.com/buttercup/buttercup-desktop/issues/62
Refs: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Implement_Proper_Password_Strength_Controls

### CODE REVIEW

**Comment by sallar** [comment]
@antoine-amara Thanks for the PR. However we were thinking about a way more similar to the password strength meter that is already inside the "Create new Entry" page (a progress bar?). What do you think?

**Comment by perry-mitchell** [comment]
Also, I don't think having any custom function to do this is a good idea. We should use a component to do this which we can use across our entire platform. I would also prefer to use one that's designed for this.

We use [this library](https://www.npmjs.com/package/owasp-password-strength-test) in our latest project @sallar - Maybe some wrapper around it could work?

**Comment by perry-mitchell** [comment]
I do believe that OWASP guidelines are the way to go at least.. I think that's safe.

**Comment by sallar** [comment]
@perry-mitchell this looks good! should we also change the existing strength meter to use this one? We currently use this: https://github.com/dropbox/zxcvbn

**Comment by antoine-amara** [comment]
Hello, thanks for the review.

@sallar , I think this is a good idea to reuse the strength meter for the master password. Maybe we have to add a label/message to inform the user has to enter a strength password to continue.

@perry-mitchell , the package [owasp-password-strength-test](https://github.com/nowsecure/owasp-password-strength-test) look good and I can use it for password validation.

I can make these change and update the PR soon:
* reuse the strength meter into the master password form.
* create a component to wrap the password form input and valid it (with owasp-password-strength-test package)

**Comment by sallar** [comment]
@antoine-amara I'm so sorry that I need to close this PR without merging it. With the way the password dialog was designed before, we couldn't add a "strength meter" to the dialog. So I had to re-code the dialog in #744 and I added a strength meter there. 

I hope this doesn't put you off and you will contribute to Buttercup again. Cheers.

**Comment by antoine-amara** [comment]
Ok @sallar thanks. I will continue to contribute when I have more time, I like this project. See you 🙂

**Pull request closed without merging**
