### PR TITLE
Use channel queue for icon downloads

### LINKED ISSUE #497: Entries list has a performance issue with icons
Since we have enabled icon support, clicking on categories with a long list of entries, causes a lag and delay. I think it's caused by the function that checks for the icon existence. I think that should be done async. Here's a gif of the issue:

lag

(there a 1-2 seconds delay between clicking "Personal" and it actually getting selected. it includes about 200 items)

### LINKED ISSUE #505: The app is taking 100% CPU and freezed
I have upgraded to the latest version, and it has an annoying behavior. When I open the app, let's say I create a new entry, the app is freezing and the laptop's fan is spinning loudly. I can't do anything inside the app for 2 minutes and then it calms down and I can continue what i was doing. It seems it has something to do with the icons fetching.

### PR DESCRIPTION
**Pull request by sallar**
Fixes #497 
Fixes #505

### CODE REVIEW

**Comment by darsain** [comment]
Any ETA on when this might ship? The app is pretty much unusable for me atm. Instantly freezes when I click on an item. Not the best first impression :)

**Comment by sallar** [comment]
@darsain This should be actually in version v1.1.0. The issue is still happening? can you give us a bit more info?

**Comment by darsain** [comment]
OS: Windows 10
Version: 1.1.0

I've imported a database form KeePass' `.kdbx` file. Buttercup loaded icons for each item, but some of them I assume failed to resolve and defaulted to this:

image

When I click on an item with this kind of icon, the whole app starts consuming one whole CPU core, freezes, and I have to kill it. Clicking on items with loaded icons doesn't do that.

An example of an item that failed to resolve an icon would be a basic username+password login with URL: https://app.net, which is a website that shut down so I guess it doesn't have favicons available anymore.

**Comment by sallar** [comment]
@darsain so the issue happens when you "click" on the item with no icon? that should not be related to the icons AFAIK. But I'll try to reproduce this. Can you please open an issue for this with the same information so we can track and work on it?

**Comment by darsain** [comment]
Actually I've just tried clicking on various items and it freezes even on the ones with icons. I'll make a new issue.

**Comment by darsain** [comment]
#520

**Pull request merged**
