### PR TITLE
Use PureComponent instead of Component #487

### LINKED ISSUE #487: Use PureComponent instead of Component
I'm trying this cool library (https://github.com/maicki/why-did-you-update) to detect unnecessary re-renders. I found and change them from `Component` to `PureComponent`. 
For example:

screen shot 2018-01-21 at 3 43 34 pm

### PR DESCRIPTION
**Pull request by alirezavalizade**
Fixes #487

### CODE REVIEW

**Comment by sallar** [comment]
Thanks @alirezavalizade. Is there any performance issues with `PureComponent` or is it fast?

**Comment by perry-mitchell** [comment]
Seems like all the docs point to it giving a performance increase in most cases, if the render function is pure.. sounds nice at least! 😁

**Comment by alirezavalizade** [comment]
@sallar Yes it's really improve app's performance. [please see this](https://stackoverflow.com/questions/41340697/react-component-vs-react-purecomponent)
And i explained in issues how to detect these re-renders.

**Comment by sallar** [comment]
Thanks @alirezavalizade @perry-mitchell. Merging this 👍

**Pull request merged**
