### PR TITLE
make links clickable

### PR DESCRIPTION
**Pull request by shimaore**
This is a tentative answer for https://github.com/buttercup/buttercup-desktop/issues/768

### CODE REVIEW

**Comment by shimaore** [comment]
#HacktoberFest #HacktoberFestBrest

**Comment by perry-mitchell** [comment]
Seems this is adding it to the **Copy** menu, which would not be great UX. What do you think @sallar - Is there a better place for this?

**Comment by sallar** [comment]
@perry-mitchell @shimaore I think it's good that we have this option as well, but we can still have the issue open and make the links clickable as well.

**Comment by perry-mitchell** [comment]
Closing this as we're preparing a v2 merge _very_ soon.. This PR doesn't align with the new codebase nor utilities used within it. Once V2 has been merged it'd be great to reconsider such a feature in a refreshed format, if needed. Thank you!

**Pull request closed without merging**
