### PR TITLE
Remember screen position (#535)

### LINKED ISSUE #535: Remember window position and size
I have 3 monitors. I'd love for buttercup to launch on a specific one with previous size and position, just like every other app does :)

Here is a simple to implement library for this:

https://github.com/mawie81/electron-window-state

### PR DESCRIPTION
**Pull request by ph1p**
**Problem**
Buttercup does not remember the last window position.
This PR should fix it.

I've tested this feature only on macos.

**Issue**
Fixes #535

### CODE REVIEW

**Comment by sallar** [comment]
Thanks @ph1p! Can we add a safety check to this? What happens if you have this on your 3rd monitor and you disconnect your screens and re-open buttercup? Will it be moved out of bounds or does electron prevent it from getting moved to far?

**Comment by ph1p** [comment]
Oh good point! I'll check it.

**Comment by ph1p** [comment]
Ok. My first test shows that electron prevents it from getting out of bounds.
- Connected 3 Monitors [_1_] [_2_] [_3_]
- Moved Buttercup from 1 to 3 and disconnected 3.
- Buttercup shows up on first one.
- Connected 3 again and buttercup shows up on this one.

**Comment by sallar** [comment]
@ph1p Awesome!

**Pull request merged**
