### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by RakotStargazer**
Added Russian translation.

### CODE REVIEW

**Comment by perry-mitchell** [comment]
Awesome @RakotStargazer! Though I don't see the locales file.. Did you forget to push it?

**Comment by perry-mitchell** [comment]
Depends on #415

**Comment by sallar** [comment]
hmm apparently `locales/ru` cant be resolved that's why tests fail. need to investigate.

**Comment by sallar** [comment]
Closing and re-opening to trigger tests

**Comment by sallar** [comment]
Oh it needs to be updated with master

**Comment by dmmmd** [comment]
@sallar you might want to do it yourself, @RakotStargazer is new to Git(Hub), it might take a while

**Comment by perry-mitchell** [comment]
I think this is probably fine to merge then - it's an ultra basic change. I'll merge and will keep an eye on the appveyor tests.

**Pull request merged**
